version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Library.API/Dockerfile
  
  uniduLibrary-db:
    image: mcr.microsoft.com/mssql/server
    container_name: SQLServer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  uniduLibrary-redis:
    image: redis
    container_name: Redis
    restart: always
    ports:
      - "6379:6379"

  uniduLibrary-seq:
    image: datalust/seq:latest
    container_name: Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 9090:80