version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: Library.API/Dockerfile
  
  uniduLibrary.db:
    image: mcr.microsoft.com/mssql/server
    container_name: uniduLibrary.db
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  uniduLibrary.Redis:
    image: redis
    container_name: uniduLibrary.Redis
    restart: always
    ports:
      - "6379:6379"