name: .NET

on:
  push:
    branches:
      - dev
      - release
  pull_request:
    branches:
      - dev
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # You can change this to the version you are using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test --configuration ${{ matrix.configuration }} --no-build

    # Add additional steps here for deployment, publishing artifacts, etc.
