name: .NET Core CI

on:
  push:
    branches:
      - dev
      - release
  pull_request:
    branches:
      - dev
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # You can change this to the version you are using

    - name: Restore dependencies
      run: dotnet restore UNIDULibrary.sln

    - name: Build
      run: dotnet build UNIDULibrary.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test UNIDULibrary.sln --configuration Release --no-build

    # Add additional steps here for deployment, publishing artifacts, etc.
